kvm:
  hosts:
    #    159.31.247.101: {vm_name: ceph-1, user_name: etudiant, user_pwd: etudiant, restore: "-",range_ip1: [101, 1] ,range_ip2: []}
    159.31.247.102: {vm_name: ceph-2, user_name: etudiant, user_pwd: etudiant, restore: "-",range_ip1: [102, 1] ,range_ip2: []}
    159.31.247.103: {vm_name: ceph-3, user_name: etudiant, user_pwd: etudiant, restore: "-",range_ip1: [103, 1] ,range_ip2: []}
    159.31.247.104: {vm_name: ceph-4, user_name: etudiant, user_pwd: etudiant, restore: "-",range_ip1: [104, 1] ,range_ip2: []}
    159.31.247.105: {vm_name: ceph-5, user_name: etudiant, user_pwd: etudiant, restore: "-",range_ip1: [105, 1] ,range_ip2: []}
    
