#cloud-config
#voir : https://cloudinit.readthedocs.io/en/latest/reference/examples.html
hostname: {{vm_name}}
#fqdn: Node1.kube.test
manage_etc_hosts: true
disable_root: false
users:
  - name: {{user_name}}
    shell: /bin/bash
    lock-passwd: false
    ssh_pwauth: True
    chpasswd: { expire: False }
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDlWCUKTeYIcn825ZVJrazTdwofZI5QVo7UNu3p5REJCeXNU7gf9jYjTC88u+z+nWsxoU9BINngQlZjF1DCsXNO5I8C2W0O87Gmd+J0Rr6Fgem84T/bh0EWie0g4gylM0pTzdYs8NWn1bQvA/i/961zhjKjUuNsBqiHmr8XvCXLApCGPR2jimKwL9KYhQBTCVIl19t8+No0Vrc7ZQbL/Kvom4oOVfzJobNEhFk8cUufDBjM/LfKZYQNDY0MtvOmwSJ59zQllDM9pUau3RBtK1BiWLvisIQjUalUjelLh7Py3UUSr3IzcPULwSluDdUzFz/OF5beBMTzUxnWcnlMMgnq1U+WEqcJP9GyQXTV6RuveQNny2Em/kzC4q7DndPrSAyLX+3rK+NqrjqEwMNT+ac+QhIvdFQ4iMr2Sj1xbbvdjC88JA0bWPFWO5kDYpJ8hSK9GVa4EvfXtbMBRoJGXhdWlog7Za9Y3eD7o8r7jeZf4Fb2Y1vblatwOkUA+mD4sUs= vjo@localhost.localdomain

chpasswd:
  list: |
     {{user_name}}:{{user_pwd}}
     root:{{user_pwd}}
  expire: False

runcmd:
  - [ cp, /home/{{user_name}}/.ssh/authorized_keys, /root/.ssh/authorized_keys ]

# package_update: true
# packages:
#    - dnf-automatic
#    - fail2ban

#systemctl status fail2ban

# written to /var/log/cloud-init-output.log
final_message: "The system is finally up, after $UPTIME seconds"
